### PR TITLE
Fixes naming issues for objects with Getters and Setters

### PR DESCRIPTION
**Pull request by bubchi89**
…/wish-tally-sheet/pull/2

### CODE REVIEW

**Comment by Yippy** [comment]
I may have to undo your PR, there are situation where the document variable is lost when calling the object Setter and getters.

image

Which prompt an error when access the current document, this occurs in Wish Tally and the new Signal Tally. This error has started to popup on the Wish Tally often, I'm not sure how the settingsSheet is broken because the error actually stats the document ID correctly.

Running Auto Import multiple times seems to bypass the issue.
image

image

image

**Comment by bubchi89** [comment]
This PR is a "pure refactor"... it literally just renames some functions. I don't see how it could possibly cause any behavioral change.

I didn't look too deeply, but maybe this post is relevant: https://www.reddit.com/r/googlesheets/comments/1f4x3en/script_started_failing/. In particular, maybe it's really just an issue with timing out because the sheet is getting bigger. It's unfortunate that google doesn't provide a bit more transparency into its internal APIs. Maybe there's a better way to debug issues with it, but I'm not super familiar with the gsheets API, at least.

IMO, a reasonable solution to this is to cache the return value of `getRange()`, or even make it a singleton (implement it in a non-static way, ideally, to avoid the singleton anti-pattern). The isEnabled cell shouldn't really change right? My guess is that gsheets already caches cell values, so it's really `getRange()` that's causing performance issues.

**Comment by Yippy** [comment]
Yeah, I know it's purely refactoring, but any changes with Google Scripts doesn't work as intended so it introduced bugs. It seems that the SettingSheet is forgotten after when wishes are completed and moving to the next banner. But oddly the first two are fine and then the third one need manual re-import, and the forth banner need re-importing too.

This has happened multiple times in exact locations, even though the code is correct it seems the Scripts somehow 'forgot' what settingsSheets is. So to avoid errors I may have to remove and go back to the original code. Then test if it's working, it could be backend Google Bug. I will let you know, as I know you worked on refactoring for me. I'm not blaming you for the bugs, I'm just reporting that Google Script works in odd ways, meaning lots of testing is required.

**Comment by bubchi89** [comment]
You're welcome to try, but I really doubt it's something like the "SettingSheet is forgotten"... what are you seeing that leads you to that conclusion? Your screenshots just make it look like the `getRange()` call fails sometimes, to me.

**Comment by Yippy** [comment]
Well isEnabled and checkPages are basic functions for autoImport, though the error state the document ID which is the current one what we want to access "settingSheet" has a error. Which mean getRange, setValue will fail with that prompt. You are right that this is a refactoring that shouldn't be effect, but I'm trying to find a solution to fix it. I may have to just resort to check if settingSheet is there with a try function, if not retrieve the file as it's 'forgotten'.

Possible that Google garbage collection just removed the variable object, so I will amend the current method as just using the settingSheets is still broken. So the multiple pages of autoimport eventually kill the settingSheets variable from what I can see.

**Comment by Yippy** [comment]
image

This looks like a bodged work, but it ran through perfectly fine, twice testing the function.

image

I've replaced all the bannerSettings setter to use the function instead.... I've put a Log output in the catch but doesn't seems to invoke anything in the Logs. But it looks to be fixed.

**Comment by bubchi89** [comment]
Yeah I don't think the issue is that settingsSheet becomes null, you'd get a different error if that was the case. I think it's simply that getRange() will fail sometimes. Perhaps because of the sheet size or just general slowness on Google's end.

The approach you're using to fix it is generally an anti-pattern (i.e. adding try-catches around functions that fail but without any clear reason why it would fail. This is brittle and generally what you want to do is to fix the underlying method), but I don't think we can do a lot better since we don't have any control here.

Personally, I would make a few changes here:
1. Push the try-catch to a lower level call than setStatusText. I'm 99% sure the issue is the getRange() call, so you can wrap that specifically.
2. Also, you can inspect the error message to make sure it aligns with the specific error we're hitting so that you don't swallow exceptions that are unrelated
3. I would change it to instead be a loop so that you can try a few times instead of only once. Something like
```
x getRangeWithRetries() {
    for (int numAttempt = 0; numAttempt < MAX_GET_RANGE_ATTEMPTS; numAttempt++) {
        try {
            return <get range call>
        } catch (e) {
             if (e.getMessage().contains(...)) {
                 log.error("Error occurred fetching range. This seems to occur non-deterministically. See <link to this thread>", e);
                 continue; // Try again
             } else {
                 log.error("Unknown error occurred fetching range", e);
                 throw e; // Propagate the error up the chain
             }
        }
    }
}
```

Lastly, I do think that a better solution here is to simply cache the result of getRange() or make it a singleton. You would want to wrap that in the for-loop above in case it fails. But it's up to you. That's certainly more work than adding a try-catch.

*edit* This issue seems related: https://issuetracker.google.com/issues/182701055
I guess I'm not sure it's getRange(), but basically whenever gsheets actually tries to access data in a sheet, it seems to sometimes fail. And so... you just need to wrap that call in some retry block like above. But the key thing is I would encapsulate it in a function with a clear name and purpose. And I would add logging to improve debugging.

**Pull request merged**
